// <auto-generated/>
// Emik.SourceGenerators.Tattoo, v2.0.7
#pragma warning disable
global using global::System;
global using global::System.Buffers;
global using global::System.Buffers.Binary;
global using global::System.Buffers.Text;
global using global::System.CodeDom;
global using global::System.CodeDom.Compiler;
global using global::System.Collections;
global using global::System.Collections.Concurrent;
global using global::System.Collections.Generic;
global using global::System.Collections.Immutable;
global using global::System.Collections.ObjectModel;
global using global::System.Collections.Specialized;
global using global::System.ComponentModel;
global using global::System.ComponentModel.Composition;
global using global::System.ComponentModel.Composition.AttributedModel;
global using global::System.ComponentModel.Composition.Diagnostics;
global using global::System.ComponentModel.Composition.Hosting;
global using global::System.ComponentModel.Composition.Primitives;
global using global::System.ComponentModel.Composition.ReflectionModel;
global using global::System.ComponentModel.DataAnnotations;
global using global::System.ComponentModel.DataAnnotations.Schema;
global using global::System.ComponentModel.Design;
global using global::System.ComponentModel.Design.Serialization;
global using global::System.Configuration;
global using global::System.Configuration.Assemblies;
global using global::System.Configuration.Internal;
global using global::System.Data;
global using global::System.Data.Common;
global using global::System.Data.Odbc;
global using global::System.Data.OleDb;
global using global::System.Data.ProviderBase;
global using global::System.Data.Sql;
global using global::System.Data.SqlClient;
global using global::System.Data.SqlTypes;
global using global::System.Deployment;
global using global::System.Deployment.Internal;
global using global::System.Deployment.Internal.Isolation;
global using global::System.Deployment.Internal.Isolation.Manifest;
global using global::System.Diagnostics;
global using global::System.Diagnostics.CodeAnalysis;
global using global::System.Diagnostics.Contracts;
global using global::System.Diagnostics.Contracts.Internal;
global using global::System.Diagnostics.Eventing;
global using global::System.Diagnostics.Eventing.Reader;
global using global::System.Diagnostics.Metrics;
global using global::System.Diagnostics.PerformanceData;
global using global::System.Diagnostics.SymbolStore;
global using global::System.Diagnostics.Tracing;
global using global::System.Diagnostics.Tracing.Internal;
global using global::System.Drawing;
global using global::System.Drawing.Configuration;
global using global::System.Drawing.Design;
global using global::System.Drawing.Drawing2D;
global using global::System.Drawing.Imaging;
global using global::System.Drawing.Printing;
global using global::System.Drawing.Text;
global using global::System.Dynamic;
global using global::System.Globalization;
global using global::System.IO;
global using global::System.IO.Compression;
global using global::System.IO.IsolatedStorage;
global using global::System.IO.MemoryMappedFiles;
global using global::System.IO.Pipes;
global using global::System.IO.Ports;
global using global::System.Linq;
global using global::System.Linq.Expressions;
global using global::System.Management;
global using global::System.Management.Instrumentation;
global using global::System.Media;
global using global::System.Net;
global using global::System.Net.Cache;
global using global::System.Net.Configuration;
global using global::System.Net.Http;
global using global::System.Net.Http.Headers;
global using global::System.Net.Mail;
global using global::System.Net.Mime;
global using global::System.Net.NetworkInformation;
global using global::System.Net.Security;
global using global::System.Net.Sockets;
global using global::System.Net.WebSockets;
global using global::System.Numerics;
global using global::System.Numerics.Hashing;
global using global::System.Reflection;
global using global::System.Reflection.Context;
global using global::System.Reflection.Emit;
global using global::System.Resources;
global using global::System.Runtime;
global using global::System.Runtime.CompilerServices;
global using global::System.Runtime.CompilerServices2;
global using global::System.Runtime.ConstrainedExecution;
global using global::System.Runtime.DesignerServices;
global using global::System.Runtime.ExceptionServices;
global using global::System.Runtime.Hosting;
global using global::System.Runtime.InteropServices;
global using global::System.Runtime.InteropServices.ComTypes;
global using global::System.Runtime.InteropServices.Expando;
global using global::System.Runtime.InteropServices.TCEAdapterGen;
global using global::System.Runtime.InteropServices.WindowsRuntime;
global using global::System.Runtime.Remoting;
global using global::System.Runtime.Remoting.Activation;
global using global::System.Runtime.Remoting.Channels;
global using global::System.Runtime.Remoting.Contexts;
global using global::System.Runtime.Remoting.Lifetime;
global using global::System.Runtime.Remoting.Messaging;
global using global::System.Runtime.Remoting.Metadata;
global using global::System.Runtime.Remoting.Metadata.W3cXsd2001;
global using global::System.Runtime.Remoting.Proxies;
global using global::System.Runtime.Remoting.Services;
global using global::System.Runtime.Serialization;
global using global::System.Runtime.Serialization.Configuration;
global using global::System.Runtime.Serialization.Diagnostics;
global using global::System.Runtime.Serialization.Diagnostics.Application;
global using global::System.Runtime.Serialization.Formatters;
global using global::System.Runtime.Serialization.Formatters.Binary;
global using global::System.Runtime.Serialization.Json;
global using global::System.Runtime.Versioning;
global using global::System.Security;
global using global::System.Security.AccessControl;
global using global::System.Security.Authentication;
global using global::System.Security.Authentication.ExtendedProtection;
global using global::System.Security.Authentication.ExtendedProtection.Configuration;
global using global::System.Security.Claims;
global using global::System.Security.Cryptography;
global using global::System.Security.Cryptography.X509Certificates;
global using global::System.Security.Permissions;
global using global::System.Security.Policy;
global using global::System.Security.Principal;
global using global::System.Security.Util;
global using global::System.ServiceModel;
global using global::System.ServiceModel.Channels;
global using global::System.ServiceModel.Description;
global using global::System.ServiceModel.Dispatcher;
global using global::System.ServiceModel.Security;
global using global::System.ServiceModel.Security.Tokens;
global using global::System.StubHelpers;
global using global::System.Text;
global using global::System.Text.RegularExpressions;
global using global::System.Threading;
global using global::System.Threading.Channels;
global using global::System.Threading.Tasks;
global using global::System.Threading.Tasks.Sources;
global using global::System.Timers;
global using global::System.Transactions;
global using global::System.Web;
global using global::System.Windows;
global using global::System.Windows.Input;
global using global::System.Windows.Markup;
global using global::System.Xml;
global using global::System.Xml.Linq;
global using global::System.Xml.Resolvers;
global using global::System.Xml.Schema;
global using global::System.Xml.Serialization;
global using global::System.Xml.Serialization.Advanced;
global using global::System.Xml.Serialization.Configuration;
global using global::System.Xml.XPath;
global using global::System.Xml.XmlConfiguration;
global using global::System.Xml.Xsl;
global using global::CommunityToolkit;
global using global::CommunityToolkit.Common;
global using global::CommunityToolkit.Common.Collections;
global using global::CommunityToolkit.Common.Deferred;
global using global::CommunityToolkit.Common.Extensions;
global using global::CommunityToolkit.Common.Helpers;
global using global::CommunityToolkit.Diagnostics;
global using global::CommunityToolkit.Helpers;
global using global::CommunityToolkit.HighPerformance;
global using global::CommunityToolkit.HighPerformance.Buffers;
global using global::CommunityToolkit.HighPerformance.Buffers.Internals;
global using global::CommunityToolkit.HighPerformance.Buffers.Internals.Interfaces;
global using global::CommunityToolkit.HighPerformance.Buffers.Views;
global using global::CommunityToolkit.HighPerformance.Enumerables;
global using global::CommunityToolkit.HighPerformance.Helpers;
global using global::CommunityToolkit.HighPerformance.Helpers.Internals;
global using global::CommunityToolkit.HighPerformance.Memory;
global using global::CommunityToolkit.HighPerformance.Memory.Internals;
global using global::CommunityToolkit.HighPerformance.Memory.Views;
global using global::CommunityToolkit.HighPerformance.Streams;
global using global::Divorce;
global using global::Divorce.Fody;
global using global::DotNetProjectFile;
global using global::DotNetProjectFile.Analyzers;
global using global::DotNetProjectFile.Analyzers.Generic;
global using global::DotNetProjectFile.Analyzers.Helpers;
global using global::DotNetProjectFile.Analyzers.MsBuild;
global using global::DotNetProjectFile.Analyzers.Resx;
global using global::DotNetProjectFile.Caching;
global using global::DotNetProjectFile.CodeAnalysis;
global using global::DotNetProjectFile.Collections;
global using global::DotNetProjectFile.Conversion;
global using global::DotNetProjectFile.Diagnostics;
global using global::DotNetProjectFile.EditorConfig;
global using global::DotNetProjectFile.Git;
global using global::DotNetProjectFile.IO;
global using global::DotNetProjectFile.IO.Globbing;
global using global::DotNetProjectFile.Ini;
global using global::DotNetProjectFile.MsBuild;
global using global::DotNetProjectFile.MsBuild.Conversion;
global using global::DotNetProjectFile.Navigation;
global using global::DotNetProjectFile.NuGet;
global using global::DotNetProjectFile.Parsing;
global using global::DotNetProjectFile.Parsing.Internal;
global using global::DotNetProjectFile.Resx;
global using global::DotNetProjectFile.Syntax;
global using global::DotNetProjectFile.Xml;
global using global::Emik;
global using global::Emik.Morsels;
global using global::Fody;
global using global::FxResources;
global using global::FxResources.System;
global using global::FxResources.System.Data;
global using global::FxResources.System.Data.Common;
global using global::FxResources.System.Diagnostics;
global using global::FxResources.System.Diagnostics.DiagnosticSource;
global using global::FxResources.System.Globalization;
global using global::FxResources.System.Globalization.Extensions;
global using global::FxResources.System.IO;
global using global::FxResources.System.IO.Compression;
global using global::FxResources.System.Memory;
global using global::FxResources.System.Net;
global using global::FxResources.System.Net.Http;
global using global::FxResources.System.Runtime;
global using global::FxResources.System.Runtime.InteropServices;
global using global::FxResources.System.Runtime.InteropServices.RuntimeInformation;
global using global::FxResources.System.Runtime.Serialization;
global using global::FxResources.System.Runtime.Serialization.Primitives;
global using global::FxResources.System.Security;
global using global::FxResources.System.Security.Cryptography;
global using global::FxResources.System.Security.Cryptography.Algorithms;
global using global::FxResources.System.Threading;
global using global::FxResources.System.Threading.Channels;
global using global::FxResources.System.Threading.Overlapped;
global using global::FxResources.System.ValueTuple;
global using global::ILMerge;
global using global::InlineIL;
global using global::InlineMethod;
global using global::Internal;
global using global::JetBrains;
global using global::JetBrains.Annotations;
global using global::LocalsInit;
global using global::MS;
global using global::MS.Internal;
global using global::MS.Internal.Xml;
global using global::MS.Internal.Xml.Cache;
global using global::MS.Internal.Xml.Linq;
global using global::MS.Internal.Xml.Linq.ComponentModel;
global using global::MS.Internal.Xml.XPath;
global using global::Microsoft;
global using global::Microsoft.CSharp;
global using global::Microsoft.CSharp.RuntimeBinder;
global using global::Microsoft.Cci;
global using global::Microsoft.Cci.Pdb;
global using global::Microsoft.CodeAnalysis;
global using global::Microsoft.CodeAnalysis.Diagnostics;
global using global::Microsoft.CodeAnalysis.Text;
global using global::Microsoft.Internal;
global using global::Microsoft.Internal.Collections;
global using global::Microsoft.Internal.Runtime;
global using global::Microsoft.Internal.Runtime.Serialization;
global using global::Microsoft.Reflection;
global using global::Microsoft.Runtime;
global using global::Microsoft.Runtime.Hosting;
global using global::Microsoft.SqlServer;
global using global::Microsoft.SqlServer.Server;
global using global::Microsoft.VisualBasic;
global using global::Microsoft.Win32;
global using global::Microsoft.Win32.SafeHandles;
global using global::Mono;
global using global::Mono.Cecil;
global using global::Mono.Cecil.Cil;
global using global::Mono.Cecil.Metadata;
global using global::Mono.Cecil.PE;
global using global::Mono.Cecil.Pdb;
global using global::Mono.Cecil.Rocks;
global using global::Mono.Collections;
global using global::Mono.Collections.Generic;
global using global::Mono.Security;
global using global::Mono.Security.Cryptography;
global using global::NullGuard;
global using global::NullGuard.CodeAnalysis;
global using global::Scifa;
global using global::Scifa.CheckedExceptions;
global using global::Scifa.CheckedExceptions.Attributes;
global using global::Serilog;
global using global::Serilog.Capturing;
global using global::Serilog.Configuration;
global using global::Serilog.Context;
global using global::Serilog.Core;
global using global::Serilog.Core.Enrichers;
global using global::Serilog.Core.Filters;
global using global::Serilog.Core.Pipeline;
global using global::Serilog.Core.Sinks;
global using global::Serilog.Core.Sinks.Batching;
global using global::Serilog.Data;
global using global::Serilog.Debugging;
global using global::Serilog.Events;
global using global::Serilog.Filters;
global using global::Serilog.Formatting;
global using global::Serilog.Formatting.Compact;
global using global::Serilog.Formatting.Display;
global using global::Serilog.Formatting.Json;
global using global::Serilog.Parsing;
global using global::Serilog.Policies;
global using global::Serilog.Rendering;
global using global::Serilog.Settings;
global using global::Serilog.Settings.KeyValuePairs;
global using global::Serilog.Sinks;
global using global::Serilog.Sinks.File;
global using global::Serilog.Sinks.SystemConsole;
global using global::Serilog.Sinks.SystemConsole.Formatting;
global using global::Serilog.Sinks.SystemConsole.Output;
global using global::Serilog.Sinks.SystemConsole.Platform;
global using global::Serilog.Sinks.SystemConsole.Rendering;
global using global::Serilog.Sinks.SystemConsole.Themes;
global using global::UnitGenerator;

// Polyfills of namespaces in case dependencies are conditional.
namespace System { }

namespace System.Buffers { }

namespace System.Buffers.Binary { }

namespace System.Buffers.Text { }

namespace System.CodeDom { }

namespace System.CodeDom.Compiler { }

namespace System.Collections { }

namespace System.Collections.Concurrent { }

namespace System.Collections.Generic { }

namespace System.Collections.Immutable { }

namespace System.Collections.ObjectModel { }

namespace System.Collections.Specialized { }

namespace System.ComponentModel { }

namespace System.ComponentModel.Composition { }

namespace System.ComponentModel.Composition.AttributedModel { }

namespace System.ComponentModel.Composition.Diagnostics { }

namespace System.ComponentModel.Composition.Hosting { }

namespace System.ComponentModel.Composition.Primitives { }

namespace System.ComponentModel.Composition.ReflectionModel { }

namespace System.ComponentModel.DataAnnotations { }

namespace System.ComponentModel.DataAnnotations.Schema { }

namespace System.ComponentModel.Design { }

namespace System.ComponentModel.Design.Serialization { }

namespace System.Configuration { }

namespace System.Configuration.Assemblies { }

namespace System.Configuration.Internal { }

namespace System.Data { }

namespace System.Data.Common { }

namespace System.Data.Odbc { }

namespace System.Data.OleDb { }

namespace System.Data.ProviderBase { }

namespace System.Data.Sql { }

namespace System.Data.SqlClient { }

namespace System.Data.SqlTypes { }

namespace System.Deployment { }

namespace System.Deployment.Internal { }

namespace System.Deployment.Internal.Isolation { }

namespace System.Deployment.Internal.Isolation.Manifest { }

namespace System.Diagnostics { }

namespace System.Diagnostics.CodeAnalysis { }

namespace System.Diagnostics.Contracts { }

namespace System.Diagnostics.Contracts.Internal { }

namespace System.Diagnostics.Eventing { }

namespace System.Diagnostics.Eventing.Reader { }

namespace System.Diagnostics.Metrics { }

namespace System.Diagnostics.PerformanceData { }

namespace System.Diagnostics.SymbolStore { }

namespace System.Diagnostics.Tracing { }

namespace System.Diagnostics.Tracing.Internal { }

namespace System.Drawing { }

namespace System.Drawing.Configuration { }

namespace System.Drawing.Design { }

namespace System.Drawing.Drawing2D { }

namespace System.Drawing.Imaging { }

namespace System.Drawing.Printing { }

namespace System.Drawing.Text { }

namespace System.Dynamic { }

namespace System.Globalization { }

namespace System.IO { }

namespace System.IO.Compression { }

namespace System.IO.IsolatedStorage { }

namespace System.IO.MemoryMappedFiles { }

namespace System.IO.Pipes { }

namespace System.IO.Ports { }

namespace System.Linq { }

namespace System.Linq.Expressions { }

namespace System.Management { }

namespace System.Management.Instrumentation { }

namespace System.Media { }

namespace System.Net { }

namespace System.Net.Cache { }

namespace System.Net.Configuration { }

namespace System.Net.Http { }

namespace System.Net.Http.Headers { }

namespace System.Net.Mail { }

namespace System.Net.Mime { }

namespace System.Net.NetworkInformation { }

namespace System.Net.Security { }

namespace System.Net.Sockets { }

namespace System.Net.WebSockets { }

namespace System.Numerics { }

namespace System.Numerics.Hashing { }

namespace System.Reflection { }

namespace System.Reflection.Context { }

namespace System.Reflection.Emit { }

namespace System.Resources { }

namespace System.Runtime { }

namespace System.Runtime.CompilerServices { }

namespace System.Runtime.CompilerServices2 { }

namespace System.Runtime.ConstrainedExecution { }

namespace System.Runtime.DesignerServices { }

namespace System.Runtime.ExceptionServices { }

namespace System.Runtime.Hosting { }

namespace System.Runtime.InteropServices { }

namespace System.Runtime.InteropServices.ComTypes { }

namespace System.Runtime.InteropServices.Expando { }

namespace System.Runtime.InteropServices.TCEAdapterGen { }

namespace System.Runtime.InteropServices.WindowsRuntime { }

namespace System.Runtime.Remoting { }

namespace System.Runtime.Remoting.Activation { }

namespace System.Runtime.Remoting.Channels { }

namespace System.Runtime.Remoting.Contexts { }

namespace System.Runtime.Remoting.Lifetime { }

namespace System.Runtime.Remoting.Messaging { }

namespace System.Runtime.Remoting.Metadata { }

namespace System.Runtime.Remoting.Metadata.W3cXsd2001 { }

namespace System.Runtime.Remoting.Proxies { }

namespace System.Runtime.Remoting.Services { }

namespace System.Runtime.Serialization { }

namespace System.Runtime.Serialization.Configuration { }

namespace System.Runtime.Serialization.Diagnostics { }

namespace System.Runtime.Serialization.Diagnostics.Application { }

namespace System.Runtime.Serialization.Formatters { }

namespace System.Runtime.Serialization.Formatters.Binary { }

namespace System.Runtime.Serialization.Json { }

namespace System.Runtime.Versioning { }

namespace System.Security { }

namespace System.Security.AccessControl { }

namespace System.Security.Authentication { }

namespace System.Security.Authentication.ExtendedProtection { }

namespace System.Security.Authentication.ExtendedProtection.Configuration { }

namespace System.Security.Claims { }

namespace System.Security.Cryptography { }

namespace System.Security.Cryptography.X509Certificates { }

namespace System.Security.Permissions { }

namespace System.Security.Policy { }

namespace System.Security.Principal { }

namespace System.Security.Util { }

namespace System.ServiceModel { }

namespace System.ServiceModel.Channels { }

namespace System.ServiceModel.Description { }

namespace System.ServiceModel.Dispatcher { }

namespace System.ServiceModel.Security { }

namespace System.ServiceModel.Security.Tokens { }

namespace System.StubHelpers { }

namespace System.Text { }

namespace System.Text.RegularExpressions { }

namespace System.Threading { }

namespace System.Threading.Channels { }

namespace System.Threading.Tasks { }

namespace System.Threading.Tasks.Sources { }

namespace System.Timers { }

namespace System.Transactions { }

namespace System.Web { }

namespace System.Windows { }

namespace System.Windows.Input { }

namespace System.Windows.Markup { }

namespace System.Xml { }

namespace System.Xml.Linq { }

namespace System.Xml.Resolvers { }

namespace System.Xml.Schema { }

namespace System.Xml.Serialization { }

namespace System.Xml.Serialization.Advanced { }

namespace System.Xml.Serialization.Configuration { }

namespace System.Xml.XPath { }

namespace System.Xml.XmlConfiguration { }

namespace System.Xml.Xsl { }

namespace CommunityToolkit { }

namespace CommunityToolkit.Common { }

namespace CommunityToolkit.Common.Collections { }

namespace CommunityToolkit.Common.Deferred { }

namespace CommunityToolkit.Common.Extensions { }

namespace CommunityToolkit.Common.Helpers { }

namespace CommunityToolkit.Diagnostics { }

namespace CommunityToolkit.Helpers { }

namespace CommunityToolkit.HighPerformance { }

namespace CommunityToolkit.HighPerformance.Buffers { }

namespace CommunityToolkit.HighPerformance.Buffers.Internals { }

namespace CommunityToolkit.HighPerformance.Buffers.Internals.Interfaces { }

namespace CommunityToolkit.HighPerformance.Buffers.Views { }

namespace CommunityToolkit.HighPerformance.Enumerables { }

namespace CommunityToolkit.HighPerformance.Helpers { }

namespace CommunityToolkit.HighPerformance.Helpers.Internals { }

namespace CommunityToolkit.HighPerformance.Memory { }

namespace CommunityToolkit.HighPerformance.Memory.Internals { }

namespace CommunityToolkit.HighPerformance.Memory.Views { }

namespace CommunityToolkit.HighPerformance.Streams { }

namespace Divorce { }

namespace Divorce.Fody { }

namespace DotNetProjectFile { }

namespace DotNetProjectFile.Analyzers { }

namespace DotNetProjectFile.Analyzers.Generic { }

namespace DotNetProjectFile.Analyzers.Helpers { }

namespace DotNetProjectFile.Analyzers.MsBuild { }

namespace DotNetProjectFile.Analyzers.Resx { }

namespace DotNetProjectFile.Caching { }

namespace DotNetProjectFile.CodeAnalysis { }

namespace DotNetProjectFile.Collections { }

namespace DotNetProjectFile.Conversion { }

namespace DotNetProjectFile.Diagnostics { }

namespace DotNetProjectFile.EditorConfig { }

namespace DotNetProjectFile.Git { }

namespace DotNetProjectFile.IO { }

namespace DotNetProjectFile.IO.Globbing { }

namespace DotNetProjectFile.Ini { }

namespace DotNetProjectFile.MsBuild { }

namespace DotNetProjectFile.MsBuild.Conversion { }

namespace DotNetProjectFile.Navigation { }

namespace DotNetProjectFile.NuGet { }

namespace DotNetProjectFile.Parsing { }

namespace DotNetProjectFile.Parsing.Internal { }

namespace DotNetProjectFile.Resx { }

namespace DotNetProjectFile.Syntax { }

namespace DotNetProjectFile.Xml { }

namespace Emik { }

namespace Emik.Morsels { }

namespace Fody { }

namespace FxResources { }

namespace FxResources.System { }

namespace FxResources.System.Data { }

namespace FxResources.System.Data.Common { }

namespace FxResources.System.Diagnostics { }

namespace FxResources.System.Diagnostics.DiagnosticSource { }

namespace FxResources.System.Globalization { }

namespace FxResources.System.Globalization.Extensions { }

namespace FxResources.System.IO { }

namespace FxResources.System.IO.Compression { }

namespace FxResources.System.Memory { }

namespace FxResources.System.Net { }

namespace FxResources.System.Net.Http { }

namespace FxResources.System.Runtime { }

namespace FxResources.System.Runtime.InteropServices { }

namespace FxResources.System.Runtime.InteropServices.RuntimeInformation { }

namespace FxResources.System.Runtime.Serialization { }

namespace FxResources.System.Runtime.Serialization.Primitives { }

namespace FxResources.System.Security { }

namespace FxResources.System.Security.Cryptography { }

namespace FxResources.System.Security.Cryptography.Algorithms { }

namespace FxResources.System.Threading { }

namespace FxResources.System.Threading.Channels { }

namespace FxResources.System.Threading.Overlapped { }

namespace FxResources.System.ValueTuple { }

namespace ILMerge { }

namespace InlineIL { }

namespace InlineMethod { }

namespace Internal { }

namespace JetBrains { }

namespace JetBrains.Annotations { }

namespace LocalsInit { }

namespace MS { }

namespace MS.Internal { }

namespace MS.Internal.Xml { }

namespace MS.Internal.Xml.Cache { }

namespace MS.Internal.Xml.Linq { }

namespace MS.Internal.Xml.Linq.ComponentModel { }

namespace MS.Internal.Xml.XPath { }

namespace Microsoft { }

namespace Microsoft.CSharp { }

namespace Microsoft.CSharp.RuntimeBinder { }

namespace Microsoft.Cci { }

namespace Microsoft.Cci.Pdb { }

namespace Microsoft.CodeAnalysis { }

namespace Microsoft.CodeAnalysis.Diagnostics { }

namespace Microsoft.CodeAnalysis.Text { }

namespace Microsoft.Internal { }

namespace Microsoft.Internal.Collections { }

namespace Microsoft.Internal.Runtime { }

namespace Microsoft.Internal.Runtime.Serialization { }

namespace Microsoft.Reflection { }

namespace Microsoft.Runtime { }

namespace Microsoft.Runtime.Hosting { }

namespace Microsoft.SqlServer { }

namespace Microsoft.SqlServer.Server { }

namespace Microsoft.VisualBasic { }

namespace Microsoft.Win32 { }

namespace Microsoft.Win32.SafeHandles { }

namespace Mono { }

namespace Mono.Cecil { }

namespace Mono.Cecil.Cil { }

namespace Mono.Cecil.Metadata { }

namespace Mono.Cecil.PE { }

namespace Mono.Cecil.Pdb { }

namespace Mono.Cecil.Rocks { }

namespace Mono.Collections { }

namespace Mono.Collections.Generic { }

namespace Mono.Security { }

namespace Mono.Security.Cryptography { }

namespace NullGuard { }

namespace NullGuard.CodeAnalysis { }

namespace Scifa { }

namespace Scifa.CheckedExceptions { }

namespace Scifa.CheckedExceptions.Attributes { }

namespace Serilog { }

namespace Serilog.Capturing { }

namespace Serilog.Configuration { }

namespace Serilog.Context { }

namespace Serilog.Core { }

namespace Serilog.Core.Enrichers { }

namespace Serilog.Core.Filters { }

namespace Serilog.Core.Pipeline { }

namespace Serilog.Core.Sinks { }

namespace Serilog.Core.Sinks.Batching { }

namespace Serilog.Data { }

namespace Serilog.Debugging { }

namespace Serilog.Events { }

namespace Serilog.Filters { }

namespace Serilog.Formatting { }

namespace Serilog.Formatting.Compact { }

namespace Serilog.Formatting.Display { }

namespace Serilog.Formatting.Json { }

namespace Serilog.Parsing { }

namespace Serilog.Policies { }

namespace Serilog.Rendering { }

namespace Serilog.Settings { }

namespace Serilog.Settings.KeyValuePairs { }

namespace Serilog.Sinks { }

namespace Serilog.Sinks.File { }

namespace Serilog.Sinks.SystemConsole { }

namespace Serilog.Sinks.SystemConsole.Formatting { }

namespace Serilog.Sinks.SystemConsole.Output { }

namespace Serilog.Sinks.SystemConsole.Platform { }

namespace Serilog.Sinks.SystemConsole.Rendering { }

namespace Serilog.Sinks.SystemConsole.Themes { }

namespace UnitGenerator { }
